### ISSUE TITLE
Dwarf Mage crashing client

### ISSUE THREAD

**Issue by Daribon** [GrenderG/alpha-core#3]
As soon as you enter world with a dwarf mage, the client will crash.

This is most likely related to missing playercreateinfo for dwarf mages in the database.

**Comment by GrenderG** [comment]
Yeah as you noticed it's caused by another bug I haven't managed to fix yet, sadly. In a fresh database install, the first character you create will crash upon login unless you remove all or some items from the inventory. I'm still trying to research what's wrong, because everything appears to be okay.
